fix(InputCode): missing CodeMirror options
eleme/duang pull request #73
Opened 2017-06-02 10:12 UTC by guox191

为了支持各种 mode，CodeMirror 及插件通过 umd 引入。
为了区分 mode 的 js 文件名和 mimeModes，增了一个 addon 字段。如 `{ mode: 'java', addon: 'clike' }`

2017-06-05 02:09 UTC, jiananshi commented on src/components/InputCode.js
> +      this.editor = CodeMirror(this.element, Object.assign({
下面有一些方法，比如 `get value()` 去取 `this.editor`，如果还没有赋值就会报错

2017-06-05 02:09 UTC, jiananshi commented on src/components/InputCode.js
> +    const addon = this.addon ? this.addon : this.mode;
mode 有默认值么

2017-06-05 02:09 UTC, jiananshi commented on src/components/InputCode.js
> +      this.execQueue.forEach(item => item())
处理不了需要返回值的方法，用 Promise？

2017-06-05 08:13 UTC, guox191 commented
@jiananshi

2017-06-06 09:34 UTC, guox191 commented
求发

2017-06-06 09:53 UTC, jiananshi requested changes

2017-06-06 09:53 UTC, jiananshi commented on docs/components/README.md
> +| modelib | `String` | 支持 `mode` 的js 文件名, 默认使用 `mode` 参数寻找文件。 |
js 前面少个空格

2017-06-06 09:53 UTC, jiananshi commented on playground/index.js
> +    '/playground/apis/basic.js',
把 `/duang/` 去了在 [github pages](http://eleme.github.io/duang/playground/') 上会拿不到吧

2017-06-06 09:53 UTC, jiananshi commented on src/components/InputCode.js
> +        return resolve(this.$editor);
init 函数只会在实例化的时候运行一次：`new InputCode({ ...args })`

`this.$editor` 的赋值是在下面做的，所以这个 `if` 里的条件总会是 false

2017-06-06 09:53 UTC, jiananshi commented on src/components/InputCode.js
> +    this.editor = new Promise((resolve, reject) => {
一哥一般用 task/$task 来命名一个 Promise 实例

2017-06-06 09:53 UTC, jiananshi commented on src/components/InputCode.js
> +      setTimeout(() => editor.refresh(), 0);
既然用了 Promise 这里就不需要 setTimeout 了

2017-06-06 09:53 UTC, jiananshi commented on src/components/InputCode.js
> +    if (value == null || value === '') return; // eslint-disable-line
eqeqeq 要加，出现别的 lint 报错发现不了了

2017-06-06 10:46 UTC, guox191 commented on playground/index.js
> +    '/playground/apis/basic.js',
..原来这个目的

2017-06-06 10:48 UTC, guox191 commented on src/components/InputCode.js
> +    if (value == null || value === '') return; // eslint-disable-line
...

2017-06-06 10:58 UTC, guox191 commented
@jiananshi

2017-06-06 11:00 UTC, merged