<Feature> Add Component::OutputLink
eleme/duang pull request #9
Opened 2016-11-22 02:28 UTC by shijn

@YanagiEiichi 

- 增加 Component::OutputLink
- Component::FormSubmit 里用 `on-*` 
- Component::XPut 中去掉未声明变量 `component`

2016-11-22 03:30 UTC, YanagiEiichi requested changes

2016-11-22 03:30 UTC, YanagiEiichi commented on src/components/FormSubmit.js
> +          <jkl-button-hollow ref="backComponent" on-click="{back}">返回</jkl-button-hollow>
onclick 是 Button 基类提供的，处理函数返回一个 Promise 可以让按钮进入 busy 状态。
on-click 是原始的事件绑定，只是 addEventListener 的一个糖语法。

2016-11-22 03:30 UTC, YanagiEiichi commented on src/components/Output.js
> +    let { component, args = {}, params, query, depot, fieldMap, value } = this;
Output 里面就不要处理 fieldMap 了，所有数据通过 value 传。。

2016-11-22 03:30 UTC, YanagiEiichi commented on src/components/OutputLink.js
> +    this.element.addEventListener('click', this.onClick.bind(this));
可以直接在 template 上用 on-click 绑定事件

2016-11-22 03:30 UTC, YanagiEiichi commented on src/components/OutputLink.js
> +    return location.hash = '#' + uParams;
可以把 target 那套逻辑实现了，比如 target 为 dialog 时用对话框打开。。

2016-11-22 03:30 UTC, YanagiEiichi commented on src/components/XPut.js
> +      throw new Error(`Component args loading error with '${error.message}'`);
直接改成中文吧。。这个项目在渐渐中文化。。

2016-11-22 10:22 UTC, shijn commented
@YanagiEiichi 

都改了，另外加了 `refactor.js` 里支持 `#` 的匹配符并向下兼容

2016-11-22 17:09 UTC, YanagiEiichi requested changes

2016-11-22 17:09 UTC, YanagiEiichi commented on src/components/FormSubmit.js
> +    init() {
这个本地测过了么？我猜这么写不行。。`template` 解析完毕之后才会执行 `init`，此时错误的 `submit` 应该已经被绑定了。。`init` 改成 `beforeParse` 呢？

2016-11-22 17:09 UTC, YanagiEiichi commented on src/components/Output.js
> +    return req('Output' + component.replace(/./, $0 => $0.toUpperCase())).catch(() => {
配置文件里的 `component` 本来就是首字母大写的吧？如果不是应该改配置文件，此处可以不做兼容。

2016-11-22 17:09 UTC, YanagiEiichi commented on src/components/OutputLink.js
> +    where = JSON.stringify(refactor(where, this));
`refactor` 的第二个参数都应该是 `this.value` 么？

2016-11-23 01:43 UTC, shijn commented on src/components/FormSubmit.js
> +    init() {
你猜对了 😂 `beforeParse` 可以的

2016-11-23 01:55 UTC, shijn commented on src/components/TableCell.js
> +      case !!component: {
这里被 `Eslint` 报警了，所以加了个 block

2016-11-23 03:40 UTC, merged